### ISSUE TITLE
How to customize index.js in jasmine-trx-reporter to separately get the description of describe block and it block.. 

### ISSUE THREAD

**Issue by VinuthnaS** [papa-pep/jasmine-trx-reporter#10]
Hi Pep, 

I'm stuck in retriving the description from the spec object in index.js
THis is how i;m trying to extract the details out of spec object,

this.specDone = function (spec) {
        console.log('*----->specObj: ' + JSON.stringify(spec));
        console.log('-------->specDescription: ' + spec.description);
	console.log('--------->fullName: ' + spec.fullName);
}

the JSON.stringify(spec) gives complete details inside spec object, 
we have spec.description details as well which gives "it" block description only and which is all fine
but how do i retrieve only the describe's descrption? 
when i do spec.fullname it gives me the concatination of describe and it block's decsription.. 
please help to get only the describe block's description...

**Comment by papa-pep** [comment]
I believe that is the naming convention used by jasmine and is inherited in the reporter implementation.  You may be able to do some clever parsing of the string to get what you want.

**Comment by VinuthnaS** [comment]
Thanks a lots :)

On 02-Mar-2017 9:40 PM, "Greg Pepin" <notifications@github.com> wrote:

I believe that is the naming convention used by jasmine and is inherited in
the reporter implementation. You may be able to do some clever parsing of
the string to get what you want.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/papa-pep/jasmine-trx-reporter/issues/10#issuecomment-283697236>,
or mute the thread
