### ISSUE TITLE
Add 'require' statement to README

### ISSUE THREAD

**Issue by dclevelandpilr** [papa-pep/jasmine-trx-reporter#11]
Thank you for your work on this!

It wasn't obvious to a newbie like me that I needed to add `var trx = require('jasmine-trx-reporter');` in the `onPrepare` method. May I suggest that it be added to the example usage in the README?

**Comment by papa-pep** [comment]
Glad you are getting some use out of it!  YukonJess updated the readme for you, so I'll close the issue.
