### ISSUE TITLE
Is possible several specs in only one trx?

### ISSUE THREAD

**Issue by JoaquinLorte** [papa-pep/jasmine-trx-reporter#2]
I have to test several spec files, but the result of the latest spec overwrites the previous trx result. Is there any way that results in a unique trx are added?
exports.config = {
    directConnect: true,
    //onPrepare: function () {
    //    console.log('Adding TRX reporter');
    //    require('protractor-trx-reporter');
    //    jasmine.getEnv().addReporter(new jasmine.TrxReporter('d:/config/aa.trx'));
    //},
    framework: 'jasmine2',
    onPrepare: function (){return browser.getCapabilities().then(function (caps) {
        trx = require('jasmine-trx-reporter');
        jasmine.getEnv().addReporter(new trx(null,'ProtractorTestResults.trx', null));
    });
    },
    seleniumAddress: 'http://localhost:4444/wd/hub',
    capabilities: {
        'browserName': 'chrome',
        'chromeOptions': { 'args': ['incognito'] }
    },
    //specs: ['./Tests/Test.js'],
    specs: ['./Tests/*_spec.js'],
    defaultTimeoutInterval: 30000,
    getPageTimeout: 30000,
    allScriptsTimeout: 30000,
    //restartBrowserBetweenTests: true,
    jasmineNodeOpts: { defaultTimeoutInterval: 30000 }

};
Thank you

**Comment by papa-pep** [comment]
Hello,

In the latest version the reporter constructor takes 3 arguments: The name of the suite, the name of the file, and browser information.  If you do not specify the name of the file to be generated, it should default to being named according to the browser information and the spec name.  If you specify a file name, then I could see how the file would be continuously overridden.  I would recommend either passing null for the file name parameter or specifying some kind of unique identifier within your file name.  

Passing null would generate a file named similar to (browserinfo)_(spec name).trx.

Hope that helps,
-Greg

**Comment by JoaquinLorte** [comment]
Hello,
I needed that the result of all the suites were recorded in a single file.
I've changed four functions to achieve this. It is based on completing the
process in jasmineStarted and jasmineDone instead of suiteStarted and
suiteDone. I think you could add a new argument in the constructor to
indicate the mode. I would appreciate if this modification were implemented
to be able to continue using your module jasmine-trx-reporter now and in
future versions.

'use strict';
var trx = function () {

```
var TRX = require('node-trx'),
    fs = require('fs'),
    os = require('os');

module.exports = function (reportName, outputFile, browserStr) {
    //console.log('Adding TRX reporter: ' + reportName + ' - ' +
```

outputFile + ' - ' + browserStr);

```
    var run = {},
        computerName = os.hostname(),
        reportName = '',
        browser = browserStr,
        userName = process.env.USERNAME,
        suiteName = '';

    if (outputFile) {
        outputFile = browserStr + '_' + outputFile || 'Default.trx';
    } else {
        outputFile = null;
    }

    this.jasmineStarted = function (suiteInfo) {
        //console.log('jasmineStarted: ' + suiteInfo.totalSpecsDefined
```
- ' specs found');
          if (outputFile == null) {
              outputFile = browser + '_' + suite.description + '.trx' ||
  'Default.trx';
          }
  
  ```
      var suiteStartTime = getTimestamp(new Date());
      run = new TRX.TestRun({
          name: reportName,
          runUser: process.env.USERNAME,
          times: {
              creation: suiteStartTime,
              queuing: suiteStartTime,
              start: suiteStartTime,
              finish: suiteStartTime
          }
      });
  };
  
  this.suiteStarted = function (suite) {
      //console.log('suiteStarted: ' + suite.fullName);
  
      suiteName = suite.description;
  };
  
  this.specStarted = function (spec) {
      //console.log('specStarted: ' + spec.description);
  
      spec.startTime = new Date();
      run.times.start = getTimestamp(spec.startTime);
      if (!spec.startTime) {
          spec.startTime = spec.startTime;
      }
  };
  
  this.specDone = function (spec) {
      //console.log('specDone: ' + spec.description);
  
      spec.finished_at = new Date();
      var specRunTime = calculateRunTime(spec);
      var success = spec.failedExpectations.length === 0
      var result = {
          test: new TRX.UnitTest({
              name: suiteName + ' - ' + spec.description + ' - ' +
  ```
  
  browser,
                  methodName: spec.description,
                  methodCodeBase: 'protractor-jasmine',
                  methodClassName: suiteName,
                  description: spec.description + ' - ' + browser
              }),
              computerName: computerName,
              outcome: success ? 'Passed' : 'Failed',
              duration: specRunTime,
              startTime: getTimestamp(spec.startTime),
              endTime: getTimestamp(spec.finished_at)
          };
          if (success === false) {
              result.output = combineProperties(spec.failedExpectations,
  'message');
              result.errorMessage =
  combineProperties(spec.failedExpectations, 'message');
              result.errorStacktrace =
  combineProperties(spec.failedExpectations, 'stack');
          }
          run.addResult(result);
      };
  
  ```
  this.suiteDone = function (result) {
      //console.log('suiteDone: ' + result.fullName);
  
  };
  
  this.jasmineDone = function () {
      //console.log('jasmineDone');
      run.times.finish = getTimestamp(new Date());
      //console.log(run);
      fs.writeFileSync(outputFile, run.toXml());
  };
  
  function getTimestamp(date) {
      function pad(n) { return n < 10 ? '0' + n : n; }
      var currentDate = date !== undefined ? date : new Date(),
          month = currentDate.getMonth() + 1,
          day = currentDate.getDate();
      return (currentDate.getFullYear() + "-" + pad(month) + "-" +
  ```
  
  pad(day) + " " + pad(currentDate.getHours()) + ":" +
  pad(currentDate.getMinutes()) + ":" + pad(currentDate.getSeconds()));
      }
  
  ```
  function calculateRunTime(spec) {
      var specRunTime = (spec.finished_at - spec.startTime) / 1000;
      specRunTime = (isNaN(specRunTime) ? 0.001 : specRunTime);
  
      var newDate = new Date(null);
      var splitSeconds = specRunTime.toString().split('.');
      if (splitSeconds.length == 2) {
          newDate.setUTCSeconds(splitSeconds[0], splitSeconds[1]);
      } else {
          newDate.setUTCSeconds(splitSeconds[0]);
      }
      var dateStr = newDate.toISOString().substr(11, 12);
      return dateStr;
  }
  
  function combineProperties(collection, property) {
      var combined = '';
      for (var i = 0; i < collection.length; i++) {
          combined = combined + ' - ' + collection[i][property];
      }
      return combined;
  }
  ```
  
  };
  };
  module.exports = new trx();

Thank you for your attention
Joaquín

2015-12-02 15:46 GMT+01:00 Greg Pepin notifications@github.com:

**Comment by papa-pep** [comment]
Hello,

I now understand your issue.  I don't have this issue using TFS2015 because there is an option in the new web based build process to combine result for all of the uploaded trx files.  I am also using selenium in a grid configuration to run the tests in a sharded manner.  Please feel free to make a pull request and I'll check it out.

Thanks,
-Greg

**Comment by papa-pep** [comment]
I've merged the pull request that should satisfy this issue. Thanks!

**Comment by JoaquinLorte** [comment]
Thanks Greg!!!!
