### ISSUE TITLE
Getting TypeError: path must be a string

### ISSUE THREAD

**Issue by theretis** [papa-pep/jasmine-trx-reporter#8]
I've set up the application to generate a trx file as specified in the readme and actually the report is created. However, the test reports an error of 

> TypeError: path must be a string

and causes the test to halt and not close gracefully as expected. This appears to be generated by a second call to:

> this.writeResultFile

generated somewhere in your code after the outputFile name has become null

As a workaround, I have updated your code (in my copy) as follows:

``` javascript
this.writeResultFile = function () {
   console.log('write ' + outputFile);
     if (outputFile != null) {
       run.times.finish = getTimestamp(new Date());
       fs.writeFileSync(outputFile, run.toXml());
    }
}
```

to account for the rogue call but of course this doesn't solve the underlying issue.

Any ideas on the cause?

**Comment by papa-pep** [comment]
How is the reporter set up in your onPrepare function?

**Comment by theretis** [comment]
As requested, here is the my onPrepare:

``` javascript
    onPrepare: function () {
        var trx = require('jasmine-trx-reporter');
        return browser.getCapabilities().then(function (caps) {
            var browserName = caps.get('browserName').toUpperCase();
            var browserVersion = caps.get('version');

            console.log(browserName + ' ' + browserVersion);

            var jasmineTrxConfig = {
                reportName: 'Protractor E2E Testing - ' + browserName + " " + browserVersion,
                folder: 'output',
                outputFile: 'Protractor-Tests.trx',
                browser: browserName + " " + browserVersion,
                groupSuitesIntoSingleFile: false
            };

            jasmine.getEnv().addReporter(new trx(jasmineTrxConfig));

        });
    }
```

**Comment by papa-pep** [comment]
I don't see any issues with your config jumping out at me.  You may need to step through and figure out what is calling that function twice and why.

**Comment by theretis** [comment]
It would appear that reporter is not handling nested suites such as:

``` javascript
describe('Top Level suite', function() {
  describe('Nested suite', function() {
    it('nested spec', function() {
      expect(true).toBe(true);
    });
  });
});
```

This appears to cause the second call

**Comment by papa-pep** [comment]
Yeah, that makes sense.  We have run into some issues nesting suites in the past and now don't do it as a best practice.  We might be able to do some refactoring to be enable that scenario...but in the meantime I would suggest "de-nesting" the suites unless you have a solid reason to be doing so.

**Comment by papa-pep** [comment]
The other thing you can try is grouping your suites to output as a single file, rather than by each suite.  In the meantime I've added a check on the outputfile variable that will hopefully solve your issue.  I'll update the package soon.  Thanks.

**Comment by papa-pep** [comment]
Npm package has been updated. Closing issue.
